services:
  - type: web
    name: redetoons-stremio-addon
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: PAGE_SIZE
        value: "100"
      - key: CACHE_TTL_MS
        value: "300000"
